name: Release

on:
  push:
    # Pattern matched against refs/tags
    tags:        
      - v*
jobs:
  build:      # Push events to every tag
    runs-on: ubuntu-latest
    steps:
    - name: Changelog
      uses: scottbrenner/generate-changelog-action@master
      id: changelog
      if: env.validRelease == 'true'
      env:
        REPO: ${{ github.repository }}

    - name: Create Release
      uses: actions/create-release@v1
      if: env.validRelease == 'true'
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
          tag_name: ${{ steps.nbgv.outputs.SemVer2 }}
          release_name: Release ${{ steps.nbgv.outputs.SemVer2 }}
          body: |
            ${{ steps.changelog.outputs.changelog }}

